- dagmc/dagnav.py
- pyproject.toml
- test/test_basic.py
This PR implements a new `material` property on the `Volume` class that gives users an easy way to change the material assigned to a volume without having to manually mess around with the associated groups.
> Add material property to Volume class

- dagmc/dagnav.py
- test/test_basic.py
Short PR here adding a `category` property to the `DAGSet` class as well as adding a setter for the existing `geom_dimension` property.
> Add a category property to DAGSet

- dagmc/dagnav.py
- test/test_basic.py
If a Python class defines `__eq__` but not `__hash__`, it is not usable in sets or as a dictionary key. This PR adds the `__hash__` method to `DAGSet` so that they are hashable.
> Add `__hash__` method to DAGSet

- dagmc/dagnav.py
- test/test_basic.py
This should of course be used wisely, but it makes sense to be able to remove sets. For instance, one might want to replace group assignments entirely. This would make it easier to do so.
> Adding a method to delete sets

- dagmc/dagnav.py
- test/test_basic.py
After making a set of changes to a DAGMC model, it would be convenient to be able to write the file from the model class to incorporate all changes without accessing the `pymoab.core.Core` object. This adds a small wrapper to do so.
> Adding option to write file from the `DAGModel` class.

- dagmc/dagnav.py
- test/test_basic.py
This PR adds `forward_volume` and `reverse_volume` properties in the `Surface` class, which in turn rely on a lower-level `surf_sense` property. There was also a small bug in the `get_volumes()` method that is now fixed.
> Implement `forward_volume` and `reverse_volume` properties in Surface

- dagmc/dagnav.py
- test/test_basic.py
This PR simply adds the capability to generate multiple groups of volumes in the `DAGModel` which will help facilitate material assignment and MCNP UM model conversion.
> Add ability to create multiple groups of volumes at once

- .github/workflows/ci.yml
This appears to work using the newest release of MOAB.
Note: it probably makes sense to update the HDF5 version being used, but rebuilding it for each CI will slow things down.  The alternative gets us into more complicated CI space.
Fixes #16
> update MOAB version

- dagmc/dagnav.py
- test/test_basic.py
Improve group handling to ensure that duplicate groups with the same name are never created.
Keep a cache of Surface/Volume/Group ids to ensure that we don't reuse an ID already in use.
Makes many getter functions into properties and updates their calls.
Closes #12 
Closes #15
> Cleanup group handling and make many functions into properties

- dagmc/dagnav.py
- test/test_basic.py
This PR adds a `DAGSet.create` classmethod that can be used to create new volumes/surfaces that functions similar to the `Group.create` classmethod:
```Python
vol = dagmc.Volume.create(model, ...)
surf = dagmc.Surface.create(model, ...)
```
One thought I had regarding design is that it might be better to have `create` methods on the `DAGModel` class instead since the model always has to get passed, so that the above example would look like:
```Python
vol = model.create_volume(...)
surf = model.create_surface(...)
```
> Add DAGSet.create classmethod

- dagmc/dagnav.py
- test/test_basic.py
This PR builds on #13 to provide`create_group`, `create_volume` and `create_surface` methods on the `DAGModel` class that simply delegate to the underlying `DAGSet.create` and `Group.create` classmethods.
> Add create methods on DAGModel class

- dagmc/dagnav.py
- test/test_basic.py
If the `id` value passed to the `id.setter` is `None` automatically pick the next available ID
> Allow the id.setter to take value of None

- test/test_basic.py
Strange that this wasn't caught in CI of #21, but this contains some fixes the `test_id_safety` test.
> Fixing DAGSet ID test

- pyproject.toml
This PR updates the `pyproject.toml` file to reflect the latest changes in the project's dependencies and metadata.
- The `build-system` now requires `"setuptools_scm[toml]"` in addition to `"setuptools"` and `"wheel"`.
- The `version` field is now dynamic, managed by `setuptools_scm`.
- The `authors` field has been updated with new contributors.
- The `classifiers` field has been expanded to include more specific information about the project.
- The `requires-python` field has been added to specify the minimum Python version required.
- The `dependencies` field no longer includes `"pymoab"`.
- The `project.urls` field now includes links to the project's bug tracker and source code.
- The `tool.setuptools_scm` field has been added for `setuptools_scm` configuration.
> Update `pyproject.toml` Configuration

- dagmc/dagnav.py
- pyproject.toml
This PR removes `pymoab` from `pyproject.toml` as a dependency.
Here are the main changes made in this PR:
1. **`pyproject.toml`:** Removed `pymoab` from the list of dependencies.
2. **`dagnav.py`:** Added instructions to handle the case if `pymoab` is not found.
> Remove pymoab as a Dependency

- src/pydagmc/dagnav.py
- test/test_basic.py
This PR ensures that the groups returns from the `DAGModel.groups` attribute is indexable (it is currently a `dict_values` object). Adds a test indexing this attribute to ensure this is true.
> Ensure that groups attribute is indexable

- .github/workflows/ci.yml
- .gitignore
- README.md
- pyproject.toml
This adds a simple testing coverage report to CI.
> Test coverage report

- .github/workflows/ci.yml
This installs MOAB/PyMOAB from Conda in CI at the suggestion of @ahnaf-tahmid-chowdhury. CI turnaround is now ~90s. Nice!
> Install MOAB/PyMOAB using Conda in CI

- src/pydagmc/dagnav.py
- test/test_basic.py
Given that this is a property of the `Surface` class, the `surf_` prefix seems redundant. 
**Note: this will be a breaking change**
> Rename Surface.surf_sense property to Surface.senses

- src/pydagmc/dagnav.py
- test/test_basic.py
Title kind of says it all. I was trying to do the following today:
```python
for surf in model.surfaces:
if None in surf.surf_sense:
...
```
And had an exception raised due to a missing attribute on `NoneType` for the `None` <--> `DAGSet` comparison.
> Ensuring other types can be compared to DAGSet without raising an exception

- .github/workflows/pypi.yml
The dynamic versioning in `setuptools-scm` infers versions from tags in the repository. We'll need those in PyPI publishing workflows to produce wheels with valid version specifiers accepted by `pypa`.
https://packaging.python.org/en/latest/specifications/version-specifiers/
> Checkout repostitory tags In PyPI workflow

- pyproject.toml
The `description` in the `pyproject.toml` file was over two lines and only the first is shown in a PyPI search results.  This puts it on a single line to improve the search results.
> description on one line to avoid truncation on PyPI search results
